### ISSUE TITLE
Graves AA crashing the game

### ISSUE THREAD

**Issue by HiImNatsu** [EloBuddy/EloBuddy.Issues#1]
Graves addons bugsplat when ever i try to AA , i even tried to aa only with orbwalker ( no addon ) it still bug splat

**Comment by Hellsing** [comment]
Will take care of that tomorrow, thanks for the report!

**Comment by HiImNatsu** [comment]
love you senpai <3

**Comment by Hellsing** [comment]
Just played a bot match with Graves, no bugsplats at all, Orbwalker works.
