### ISSUE TITLE
LastHit mode attacking full life minions

### ISSUE THREAD

**Issue by PierreAndreis** [EloBuddy/EloBuddy.Issues#10]
Last hit its not freezing the lane and only last hitting. It is hitting the minions with full hp

**Comment by Hellsing** [comment]
I've tested it and can only tell you that it's properly last hitting only, not attacking any minion which could not be killed with just one auto attack. Please check if it's a addon which is forcing any other orbwalker mode or check your key bindings again for the orbwalker.

**Comment by PierreAndreis** [comment]
sorry, i had jungle clear with lasthit. Its working properly now

**Comment by Hellsing** [comment]
Glad to hear you have fixed it
