### ISSUE TITLE
Obj_Ai_Base.FlatMagicReduction

### ISSUE THREAD

**Issue by mztikk** [EloBuddy/EloBuddy.Issues#100]
Returns 0

**Comment by jachicao** [comment]
Thank you for your report, sadly i saw it too late.
We will see if is still broken for 6.10.

**Comment by mztikk** [comment]
Still bugged...

**Comment by jachicao** [comment]
for what do you need that value?

**Comment by mztikk** [comment]
Calculating damage. Cuz every function to do that returns wrong values so I wanted to write my own just to find out that the needed stuff is broken.
