### ISSUE TITLE
Orbwalker orbwalking for a champion outside the range

### ISSUE THREAD

**Issue by mrarticuno** [EloBuddy/EloBuddy.Issues#103]
Sometimes the orbwalker is orbwalking for the highest priority even in the other side of the map.

**Comment by stefsot** [comment]
Do you have any video or something? Cause I can't replicate it.
Maybe a better explanation could help.

**Comment by mrarticuno** [comment]
i will try to make a video on it.

**Comment by jachicao** [comment]
if you get the error again let me know, there was a problem with Champion enum.
