### ISSUE TITLE
Massive fps drop under tower

### ISSUE THREAD

**Issue by HDown-idk** [EloBuddy/EloBuddy.Issues#105]
When tower (laser tower) at base start attacking minions i lost my fps so hard. Slideshow detected.
Same ppl have this problem. I believe you check this.

**Comment by stefsot** [comment]
what addon are you using?

**Comment by HDown-idk** [comment]
No one. View BuddyBox, they say about it. 
same https://www.elobuddy.net/topic/30822-fps-drop/?do=findComment&comment=218243
