### ISSUE TITLE
SDK Bootstrap Error

### ISSUE THREAD

**Issue by ghost** [EloBuddy/EloBuddy.Issues#109]
Mario [Hu3] told me to post this problem here.

The errors here always throw the same exceptions, regarding the SDK.

I was thinking one of the dlls were corrupt, but a lot of other newer people seem to not have the same issue.

```
Error] SDK Bootstrap error:
System.TypeInitializationException: The type initializer for 'EloBuddy.SDK.Menu.
ThemeManager' threw an exception. ---> SharpDX.SharpDXException: HRESULT: [0x887
6086C], Module: [SharpDX.Direct3D9] ApiCode: [D3DERR_INVALIDCALL/InvalidCall],
Message: Unknown
```

Here's a screenshot of the rest of this message, since I am not able to find the logs that contain this information, and I'm not about to type that up: 

![image](https://cloud.githubusercontent.com/assets/6255683/16105177/9887d8da-334d-11e6-8d17-019bb7cae189.png)

**Comment by stefsot** [comment]
try installing this: https://www.microsoft.com/en-us/download/details.aspx?id=34429
let me know if it fixes the problem
