### ISSUE TITLE
EntityManager.MinionsAndMonsters.CircularFarmPosition broken

### ISSUE THREAD

**Issue by MarioGK** [EloBuddy/EloBuddy.Issues#11]

**Comment by Hellsing** [comment]
Could you please provide more info such as a code snippet on which it fails? Thanks.

**Comment by MarioGK** [comment]
Using this code : http://puu.sh/mLdiS/e6cbfc94ad.png

Video: http://puu.sh/mLdsm/dd599e1fb1.mp4 or https://youtu.be/pCRWnczo85c

**Comment by Hellsing** [comment]
Tested several times, can not confirm that it's broken.
