### ISSUE TITLE
Game.GameID broken

### ISSUE THREAD

**Issue by 0xnobody** [EloBuddy/EloBuddy.Issues#111]
Game.GameID doesn't work

**Comment by stefsot** [comment]
why do you need it?

**Comment by 0xnobody** [comment]
distinguishing different games - if I want to keep a file for only one game, and delete it on inject if the gameid is different. Tried with Player.Instance.NetworkID, but it doesn't change per game.

**Comment by finndev** [comment]
Fixed in next update (few hrs)
