### ISSUE TITLE
[Loader] Option to disable sandbox

### ISSUE THREAD

**Issue by whosdatdev** [EloBuddy/EloBuddy.Issues#118]
Please add an option to the loader to disable the sandbox (default: sandbox on). This will be useful for private stuff that just needs more permissions, e.g. access to a website (like a central webserver for bots running on multiple machines).

**Comment by Hellsing** [comment]
And usefull for private addons with custom auth servers and encryped addons so you can sell stuff, no ty.

**Comment by whosdatdev** [comment]
Which is exactly why the sandbox should always be and stay on for the masses. I just feel like it ruins a lot of possibilities for people who build custom addons that need to communicate with the rest of their infrastructure etc

Edit: i misread your message, i get your point now :S that being saio, the concept works for ls (they do not have underground communities that sell scripts afaik)
