### ISSUE TITLE
Spell.Skillshot.AllowedCollsionCount broken

### ISSUE THREAD

**Issue by MarioGK** [EloBuddy/EloBuddy.Issues#12]
I`m using this :
            Q = new Spell.Skillshot(SpellSlot.Q, 1175, SkillShotType.Linear, 250, 1200, 80)
            {
                AllowedCollisionCount = 2, MinimumHitChance = HitChance.High
            };
but it`s casting when it will hit 3-4 minions between the player and target

**Comment by Hellsing** [comment]
Thanks for reporting, assigning @stefsot with this case.

**Comment by stefsot** [comment]
seems to work as expected ![alt tag](http://i.imgur.com/0K2OBSJ.jpg)

**Comment by MarioGK** [comment]
Using this code http://puu.sh/mLcEM/5d4c0041a4.png

Videos : http://puu.sh/mLcEH/4c8f742e4a.mp4 or https://youtu.be/5DL97_XE36g

Just Go to the ~0:50 secs

**Comment by stefsot** [comment]
oh yes, you should put AllowedCollisionCount to 1 not 2
AllowedCollisionCount means how many targets it can hit excluding the target (the target is not considered collision)

**Comment by MarioGK** [comment]
Well, i changed the code and it still wrong :(
Code : http://puu.sh/mLz8p/95f6517913.png
Video: http://puu.sh/mLyTm/7255dfd1f2.mp4

**Comment by stefsot** [comment]
that's odd, are you sure you are using that code??

**Comment by MarioGK** [comment]
Yeah pressed F8 like 2 times before recording
