### ISSUE TITLE
Can't locate TW's new client location

### ISSUE THREAD

**Issue by partment** [EloBuddy/EloBuddy.Issues#125]
My location is D:\Program Files (x86)\GarenaLoLLCUTW

**Comment by stefsot** [comment]
Can you please provide the full path of "League of Legends.exe" file?
Thank you.

**Comment by partment** [comment]
D:\Program Files (x86)\GarenaLoLLCUTW\GameData\Apps\LoLLCUTW\Game\League of Legends.exe

**Comment by stefsot** [comment]
New updated pushed, let me know if it fixed the issue.

**Comment by partment** [comment]
![elobuddy loader_2016-12-13_23-45-47](https://cloud.githubusercontent.com/assets/5278061/21147016/93d23a40-c18e-11e6-809b-21e81e8b1714.png)

No, still can't locate.

**Comment by stefsot** [comment]
let me know if it works now

**Comment by partment** [comment]
NO
![elobuddy loader_2016-12-20_23-23-52](https://cloud.githubusercontent.com/assets/5278061/21356139/7d495cae-c70b-11e6-8590-adc4a0c2df35.png)

**Comment by TonyRL** [comment]
Fixed in https://github.com/EloBuddy/EloBuddy.Dependencies/commit/a6533b1e2ae0593056b31ff33190505f1d3bad49
