### ISSUE TITLE
Orbwalker sometimes ignoring killable minions with low life

### ISSUE THREAD

**Issue by bebetoalves** [EloBuddy/EloBuddy.Issues#13]
Tested with several champions specifically with the Lux and the Last Hit it leaves the minion with one of life and not kill, simply ignores. This also happens with other champions, ignore the minion with one of life and focus on the other that neither gave to kill.

**Comment by Hellsing** [comment]
This will be fixed in future versions of the Orbwalker, thanks for reporting anyways!

**Comment by jachicao** [comment]
Has been fixed.
