### ISSUE TITLE
All issues of Game.OnNotify

### ISSUE THREAD

**Issue by FurkanS1821** [EloBuddy/EloBuddy.Issues#130]
- [ ] OnChampionKill is fired before OnChampionKillPre, and OnChampionKillPast is not fired
- [ ] OnChampionLevelUp is not fired
- [ ] OnCriticalStrike is fired when Summoner2 is cast
- [ ] OnDamageTaken/Given not working
- [ ] OnDampenerRespawnSoon is fired when inhibitor is destroyed
- [ ] OnDampenerRespawn is fired when inhibitor is respawning soon
- [ ] OnDampenerDamage is fired when inhibitor is respawned
- [ ] OnGoldSpent/Earned is not fired
- [ ] OnItemConsumablePurchased is fired when Summoner1 is cast
- [ ] OnItemGroupChange is fired 11 times in once every 1 minute
- [ ] OnItemGroupChange is fired on recall cast time is over
- [ ] OnRedBuffAcquiredFromNeutral is fired on any neutral camp
- [ ] OnShopMenuOpen is fired when shop is closed
- [ ] OnShopItemSubstitutionChange is fired when shop is opened
- [ ] OnSuperMonsterKill is fired as the crab in the river is dead (lol?)
- [ ] OnTurretDamaged and OnMinionDenied is fired on turret death, OnTurretDie is not fired
- [ ] OnTurretKill is not fired

**Comment by TonyRL** [comment]
#114

**Comment by finndev** [comment]
Fixed in the next update
