### ISSUE TITLE
SDK.Menu.Values missing ComboBox

### ISSUE THREAD

**Issue by Hellsing** [EloBuddy/EloBuddy.Issues#15]
The current menu is missing a ComboBox for easier handling of multiple choices, right now we have to use a slider and some workarounds for this.

Assigning myself with this.

**Comment by coman3** [comment]
also buttons are missing, would be nice to "Reset" thing etc. (without a work arround)

**Comment by Hellsing** [comment]
The reset button was a planned feature aswell, so every page would have a reset button by default, but that would be a new issue/suggestion :P

**Comment by Hellsing** [comment]
Already added now
