### ISSUE TITLE
Click limiter at core doesn't change sometimes unless you change it.

### ISSUE THREAD

**Issue by JodyJazz** [EloBuddy/EloBuddy.Issues#16]
I normally play with 4 click but it always starts the game with 20-25 even it shows 4. I change it to 5 and to 4 again, then I can see the difference and it becomes 4. I don't know if this is a bug or something about me.

**Comment by Hellsing** [comment]
"Core" does not include a click limiter, could you explain what you are using to limit the clicks?

**Comment by JodyJazz** [comment]
'ticks per second' at the core menu

**Comment by Hellsing** [comment]
That is not a click limiter, ticks per second means how often the game event Game.OnTick should be called per second. By default it's set to 25 ticks per second, which means in one second the event is being triggered 25 times. This has nothing to do with click limiting.

You may look for Orbwalker -> Delay between movements in milliseconds
