### ISSUE TITLE
Obj_AI_Base.GetBuffCount("buffName") returns -1

### ISSUE THREAD

**Issue by nnduyquang** [EloBuddy/EloBuddy.Issues#2]
I use getbuffcount("nasusqstack") to get stack of nasus but it always return 0. Did something wrong about getbuffcount() or my mistake? P/s i try to fix code of karmapanda, sorry for my bad english

**Comment by Hellsing** [comment]
If that's the case then Finn has to check for any issues with specifically Nasus, thanks for the report anyways, even though it's not a SDK function your are reporting here.

**Comment by Hellsing** [comment]
I have just verified this and it seems like it's only GetBuffCount which is broken as my tool still shows the correct buff amount and names:

![alt tag](http://puu.sh/mJl4S/f8922c39b5.png)

**Comment by finndev** [comment]
fixed in the patch 6.2 binaries
