### ISSUE TITLE
Orbwalk stuttering/not attacking with jinx (only tried ashe and jinx)

### ISSUE THREAD

**Issue by deniz5316** [EloBuddy/EloBuddy.Issues#22]
One GIF is showing more than 1000 words :tada: 

I only tried ashe and jinx so far and it only happened to jinx with every single Jinx addon, ashe is working

**Comment by ghost** [comment]
https://www.elobuddy.net/topic/13590-orbwalker-problem-careful-2812016/

Confirmed?

**Comment by HiImNatsu** [comment]
same here

**Comment by Hellsing** [comment]
I am investigating in this now, thanks for the report.

**Comment by Hellsing** [comment]
Also removed the gif from the issue because it contained your summoner name

**Comment by deniz5316** [comment]
https://www.elobuddy.net/topic/13480-ticks-per-second/?p=112551

could you remove the gif from there too?
