### ISSUE TITLE
Separate menu config files for addons

### ISSUE THREAD

**Issue by plsfixrito** [EloBuddy/EloBuddy.Issues#27]
Instead of having all addons configs saved on one file that is
appdata elobuddy/MenuSaveData/SerializedMenu.ebm

to have every addon it's own save menu so we can reset the addons we want easily.

like for ex
MenuSaveData/Jinx.ebm
MenuSaveData/Evade.ebm
etc...

**Comment by Hellsing** [comment]
Implemented
