### ISSUE TITLE
NavMesh.GetCell() returning coords with slight offset

### ISSUE THREAD

**Issue by Hellsing** [EloBuddy/EloBuddy.Issues#30]
Using my Dev-a-lot tool I can visualize the game grid, this clearly shows that the NavMesh cells are off by 1 or 2 units, this is also a reason why some Vayne Addons are failing the Condemn.

Video with proof: http://puu.sh/mQBYb/73694247fc.mp4

**Comment by finndev** [comment]
fixed in patch 6.3 binaries
