### ISSUE TITLE
Player.Instance.AutoAttackTargettingFlags

### ISSUE THREAD

**Issue by ghost** [EloBuddy/EloBuddy.Issues#31]
Not sure how this is supposed to behave:

**Code**:
`if (Player.Instance.AutoAttackTargettingFlags != 0)
    Logger.Debug(Player.Instance.AutoAttackTargettingFlags.ToString());`

**Result**:
No output. (Flags are always 0)

**Expected Result:**
Output during an auto attack.

**Comment by Hellsing** [comment]
I'll let @finndev review this issue, thanks for the report!

**Comment by finndev** [comment]
fixed in the upcoming 6.3 binaries
