### ISSUE TITLE
Shop.OnBuyItem && Menu scrolling

### ISSUE THREAD

**Issue by iRaxe** [EloBuddy/EloBuddy.Issues#32]
Shop.OnBuyItem when triggers to update menu will bug.
- Example on Activator page of OKTR AIO

**Comment by Hellsing** [comment]
I expected a more detailed report from you but okay.

Please add code snippets on how you can reproduce the bug and what the bug actually is, like where does the menu bug?

Thanks for the report anyways.

**Comment by coman3** [comment]
What happens is when you add controls to the menu, after `OnLoadingComplete`, such as `OnBuyItem`, the menus height bugs out and you can't scroll down below the new controls.
