### ISSUE TITLE
Kalista - Bound for Eternity [Kalista]

### ISSUE THREAD

**Issue by Sitibi** [EloBuddy/EloBuddy.Issues#34]
1. Stacks E does not appear on  HP bar.
   1. Check  calculation of E, it is false.

**Comment by Hellsing** [comment]
This is not an EloBuddy issue, please report it to the authors own GitHub repo.

**Comment by Sitibi** [comment]
But no one checks bugs that I write to the forum. Nobody cares.

**Comment by Hellsing** [comment]
Just open the addon's GitHub repo, there you can find an issue tracker similar to this one here and you can report it there
