### ISSUE TITLE
[Bug]Health Bar Y offset is broken

### ISSUE THREAD

**Issue by MarioGK** [EloBuddy/EloBuddy.Issues#35]
You can use anything that has something that draws on the health bar to see it, i think it is pretty simple so i wont give any snippets, and X offset seems to be fine

**Comment by finndev** [comment]
Invalid.

HPBarYOffset returns the proper offset, however sometimes from patch to patch you might need to move the Y offset by a small value. Not much I can do about it.

Tracker by Fluxy looks fine to me as well.
