### ISSUE TITLE
Excessive Caching and Net usage

### ISSUE THREAD

**Issue by ghost** [EloBuddy/EloBuddy.Issues#38]
%appdata%\EloBuddy\Repositories

And it reconnects to github EVERYTIME to check for new updates, so whats the point of having the entire repo cached, when Im pretty sure the entire repo is redownloaded (Including all their other plugins by that author) every time you install one.

Needs optimization badly.

Edit:
It even includes the .git so all previous versions are cached as well? GDI guys your better than this!

**Comment by KoalaHuman** [comment]
What if github is down?

**Comment by ghost** [comment]
As previously experienced, github being down breaks EB completely, and is an entire different issue.

**Comment by KoalaHuman** [comment]
Shouldn't cache be used whenever github is down?

**Comment by ghost** [comment]
1) I dont think its even used at all, hence why its an issue,
and
2) Caching isn't storing a backup, its keeping relevant files at hand. The .git structure files, and all addons from each author you downloaded one addon from is not "relevant", its excessive.

**Comment by coman3** [comment]
Personally i agree the loader could do with some performance improvements, but please note that EloBuddy is still in development and has higher priorities such as lasthitting, damage library etc. that will also make the user experience much more enjoyable :smile: 

I will leave this issue open though, so in the future we can access this problem, Thank you.

**Comment by ghost** [comment]
I really think the time the system takes to cache everything each time you install a mod could save a lot of users in aram of having to reload after game starts because they couldnt finish downloading their champion repo (of under 5 mb with a 100 mbps connection) within the 60 seconds it takes to get in game.

I find it a major user experience issue and not a low priority, but thats my opinion.

Edit: 

> I will leave this issue open though, so in the future we can access this problem, Thank you.
> @coman3 Since when have you been an EB Authority? Last I checked you weren't.

**Comment by stefsot** [comment]
a lot of optimizations were made weeks ago when the new installer was implemented
