### ISSUE TITLE
Drawing.WorldToMinimap

### ISSUE THREAD

**Issue by PierreAndreis** [EloBuddy/EloBuddy.Issues#4]
I think minimap drawings are broken

**Comment by mrarticuno** [comment]
Are not broken, just not implemented :)

**Comment by coman3** [comment]
i have used them before though (Patch 5.24)? I think its just the WorldToMinimap thats not working...

**Comment by Hellsing** [comment]
That is a known Core bug and is being fixed by Finn, thanks for the report anyways!

**Comment by pipe01** [comment]
Meanwhile I think I'm gonna make my own method.

**Comment by finndev** [comment]
fixed in the patch 6.2 binaries

**Comment by pipe01** [comment]
Thank you very much! You are an awesome dev.
