### ISSUE TITLE
'HeroManager' Does not exist

### ISSUE THREAD

**Issue by dragitz** [EloBuddy/EloBuddy.Issues#43]
Did you change the code ?

Btw here's my logs:

Full log: http://pastebin.com/raw/ENV32Xp1

The logs are in italian, but the only problem is that HeroManager does not exist

**Comment by coman3** [comment]
Yes it was removed just recently

**Comment by dragitz** [comment]
May I ask:
Is there any way I can replace it with something else?

This is the only string that got affected by this

> HeroManager.Enemies.FirstOrDefault(hero => hero.IsValidTarget(500f)

**Comment by coman3** [comment]
EntityManager.Heroes.Enemies

**Comment by dragitz** [comment]
Oh man, thank you !

**Comment by coman3** [comment]
No worries, probably should close this thread now though :)
