### ISSUE TITLE
Drawing.DrawText size ignored

### ISSUE THREAD

**Issue by coman3** [EloBuddy/EloBuddy.Issues#49]
Pretty simple error, the `size` parameter of `Drawing.DrawText(Vector2 pos, Color color, String text, float size);` is ignored..

**Comment by Hellsing** [comment]
Thanks for reporting, @finndev will take care of that!

**Comment by finndev** [comment]
When I added that specific function to the API I did not notice that the DrawText function of the game itself that EloBuddy.Core is calling does not take a size argument. The method with the signature above will be deprecated in Patch 6.8 and fully removed 3 patches afterwards (size argument removed).
