### ISSUE TITLE
Orbwalk is not working correct for Azir's Solider

### ISSUE THREAD

**Issue by Sivuu** [EloBuddy/EloBuddy.Issues#5]
When I use orbwalk for Azir's solider , the lasthitable creep is not correct to attack so too many missing attack on creep.
I have some solution for this like add Orbwalk function to attack normal.Because Orbwalk.ForcedTarget just focus on target but not attack it

**Comment by Hellsing** [comment]
I will take a look at the Azir handling soon as it has been changed by someone else so I don't know what could be wrong with it yet, thanks for the report!

**Comment by ghost** [comment]
When playing WuAzir I noticed repeated forced movements towards nexus turrets (probably attack commands) and even right clicking (and flee) failed to release the champions movement back to me. WujuSan claims this is orbwalker related, so Im leaving this here as a heads up, as it may have to do with this issue too.

**Comment by Hellsing** [comment]
It might be that the Soldiers try to attack the turrets which is not possible, I will look into this soon

**Comment by Sivuu** [comment]
I think the problems happened here is the damage calculated is wrong (need to correct it for Azir's W skill or add some function that permit developer can command normal attack without Orbwalk )

**Comment by jachicao** [comment]
Fixed
