### ISSUE TITLE
Elobuddy.SDK cannot load

### ISSUE THREAD

**Issue by sensimela** [EloBuddy/EloBuddy.Issues#52]
Here's my problem, I got stuck at loading SDK and league won't even load, last week EB is still stable to use when a new update of SDK last 3 days, SDK won't load anymore and even league won't load. Please help me with this problem reinstalled everything, cleared appdata and turned off antivirus.

I have
Net. Framework 4.6
League version 6.3.0.240

Addons checked:
Magician Ryze 
TrackerBuddy
Evadeplus
RecallTracker

Hope there's a solution to this

**Comment by sensimela** [comment]
Help!

**Comment by sensimela** [comment]
Why is this closed? This was not yet solved please

**Comment by coman3** [comment]
have you tried launching without any addons installed at all?

**Comment by sensimela** [comment]
yes already tried running without addons but SDK won't really load!

**Comment by coman3** [comment]
is there any kind of error log within the console?
