### ISSUE TITLE
Draw LastHit minion out of AA range.

### ISSUE THREAD

**Issue by ibonzanino** [EloBuddy/EloBuddy.Issues#55]

**Comment by jachicao** [comment]
Could you please tell me what champion did you use and a screenshot as example? I've checked the code and doesn't happen on my pc.

**Comment by Hellsing** [comment]
It's drawing lasthit minions out of AA range + 500 units, everything else would be too CPU intense to calculate when it's not even on screen.

**Comment by ibonzanino** [comment]
LastHit key active and not draw out of AA range. [https://i.gyazo.com/83c6bafde55e21a6c8b7a021df6cbaf5.jpg](https://i.gyazo.com/83c6bafde55e21a6c8b7a021df6cbaf5.jpg)

**Comment by Hellsing** [comment]
Are you sure you have it enabled ingame in the Orbwalker menu?

**Comment by ibonzanino** [comment]
Yes, see: [https://i.gyazo.com/3565c0de906b8278be0708591be3960b.gif](https://i.gyazo.com/3565c0de906b8278be0708591be3960b.gif)

**Comment by jachicao** [comment]
Well, since your issue was drawing lasthit minions out of aa range, that isn't a problem...
