### ISSUE TITLE
Loading Screen freezing at 100%

### ISSUE THREAD

**Issue by swordkillz** [EloBuddy/EloBuddy.Issues#6]
While I have the script injected as I start the game, the match loading screen shows everything normal except for the fact that the champion loading for my character remains 0% for 5 minutes. I had to relog without the Elobuddy Injection in order for the percentage to become 100%. As I am in the game, I have to manually change the inject settings to inject which requires a minute or two to load up successfully. In that time, I have wasted between 4-5 minutes of the laning phase and my enemies start snowballing due to the time lost in being unable to inject during loading screen.

Any solutions?

**Comment by Hellsing** [comment]
Do you have any toaster loading addon installed?

**Comment by swordkillz** [comment]
No. The only applications open are Elobuddy and League of Legends client open.

**Comment by Hellsing** [comment]
Can you reproduce the error when you have no addons installed, like a fresh EloBuddy installation? Also, which region and version are you on?

**Comment by swordkillz** [comment]
Never mind, issue fixed with clean install. Thanks for consideration.
