### ISSUE TITLE
Irregular Hero.IsVisible Behavior

### ISSUE THREAD

**Issue by ghost** [EloBuddy/EloBuddy.Issues#60]
**Code:**

```
Logger.Debug(hero.Name + " " + hero.IsVisible);
```

Expected result:
No output.
Result:
![](http://i.imgur.com/JcYGY4r.jpg)

When a hero is in fog they should not be visible, right?

**Comment by jachicao** [comment]
Hello, IsHPBarRendered has the purpose used for IsVisible. @finndev can answer better :).

**Comment by MarioGK** [comment]
I have some experience with it, as you see the corpse of blitzcrank will be at the position that he died until he respawn so if you use !blitz.IsDead will solve that problem, or as iCreative said use blitz.IsHPBarRendered

**Comment by ghost** [comment]
Blitzcrank was not dead or his profile pic would be above minimap. Please don't assume.
