### ISSUE TITLE
[IMPORTANT] Loader Issue (BUG / LANGUAGE) !

### ISSUE THREAD

**Issue by AlistaireAlexopoulos** [EloBuddy/EloBuddy.Issues#63]
The Greek Language is not detected by the translations. 

Thread.CurrentThread.CurrentCulture returns el-GR maybe you added gr or only GR on language if you do it like this.

Please fix, Greek community is very sad about no translation!

**Comment by stefsot** [comment]
There is currently no greek translation, that's why you can't view it.

I will try to add it soon.
