### ISSUE TITLE
Close the client  with the api.

### ISSUE THREAD

**Issue by devakumetsu** [EloBuddy/EloBuddy.Issues#68]
With the new changes made to the Sandbox (good job on that); we cant close the client at the end of game.

**Comment by coman3** [comment]
Yea personally i agree, being able to close the game client would be nice, i haven't tried everything such as killing the process, etc.. But im sure its possible (even with the current Sandbox changes).  

Ill post back here if i hear anything / manage to find a way :)

**Comment by Hellsing** [comment]
I have forwarded this issue to @finndev, I'm pretty sure he will add some kind of API like Game.Close() soon for you.

**Comment by finndev** [comment]
Added in patch 6.5 binaries
