### ISSUE TITLE
League Version for SG/GARENA

### ISSUE THREAD

**Issue by devin9086** [EloBuddy/EloBuddy.Issues#7]
Recently as of 22 JAN 2016, Garena has released a Version 6.1 Hot-fix, From 6.1 -> 6.1.0.499

**Comment by Hellsing** [comment]
Thank you for the report, Finn is taking care of it now!

**Comment by finndev** [comment]
updated: https://github.com/EloBuddy/EloBuddy.Dependencies/commit/59063885a3a67b8565835e3171e4a1f905ad286d
