### ISSUE TITLE
Something for finndev ^^

### ISSUE THREAD

**Issue by Andrijano1** [EloBuddy/EloBuddy.Issues#71]
# 

Exception occured! EloBuddy might crash!

Type: System.NullReferenceException
Message: Object reference not set to an instance of an object.

Stracktrace:
   at AutoBuddy.AutoWalker.UseHeal()
   at AutoBuddy.MainLogics.Survi.Game_OnTick(EventArgs args)
#    at EloBuddy.Game.OnGameTickNative()
# 

Exception occured! EloBuddy might crash!

Type: System.NullReferenceException
Message: Object reference not set to an instance of an object.

Stracktrace:
   at AutoBuddy.AutoWalker.UseHeal()
   at AutoBuddy.MainLogics.Survi.Game_OnTick(EventArgs args)
#    at EloBuddy.Game.OnGameTickNative()
# 

Exception occured! EloBuddy might crash!

Type: System.NullReferenceException
Message: Object reference not set to an instance of an object.

Stracktrace:
   at AutoBuddy.AutoWalker.UseHeal()
   at AutoBuddy.MainLogics.Survi.Game_OnTick(EventArgs args)
#    at EloBuddy.Game.OnGameTickNative()

[EB-Core] Exception at Champion::Hero. Hero not found: , please report to finndev
[EB-Core] Exception: Must specify valid information for parsing in the string.

**Comment by Hellsing** [comment]
AutoBuddy causes this...

**Comment by Andrijano1** [comment]
Sry didnt know, I thought something in Eb-Core , because last sentance

**Comment by Hellsing** [comment]
Nope, you read the stack from bottom to top, stopping at entries which look suspicious, Game.OnTick is just the event being triggered, moving forward to AutoBuddy.MainLogics.Survi.Game_OnTick which does not cause the issue as the next and final entry must throw it as it has no parameters AutoBuddy.AutoWalker.UseHeal()
