### ISSUE TITLE
SDK Boostrap Error:

### ISSUE THREAD

**Issue by Sordruther** [EloBuddy/EloBuddy.Issues#73]
Error Pls Help :  http://prntscr.com/ae5418

i tried Use Any Script and the same error i cant change anything in the shift menu because appear only the menu when i click orbwalker or any other thing i cant change any configs when i click space to combo dont work

**Comment by coman3** [comment]
This has been fixed, it was a temporary issue :)

**Comment by commonsharp** [comment]
https://github.com/EloBuddy/EloBuddy.Issues/issues/78
