### ISSUE TITLE
I just reinstalled EB in 1 month and I get this???

### ISSUE THREAD

**Issue by ghost** [EloBuddy/EloBuddy.Issues#74]
Can't even start this

https://gyazo.com/5b7e1f9a3d4e7323f8956c5df472ef55

**Comment by ghost** [comment]
Theres a bug in the loader, its being fixed.

**Comment by Hellsing** [comment]
This is now fixed: [https://www.elobuddy.net/topic/20488-errors-while-updating-03122016/](url)
