### ISSUE TITLE
FPS Drop

### ISSUE THREAD

**Issue by Requital** [EloBuddy/EloBuddy.Issues#8]
I have fps drops, its not an addon problem 'cause i have them on every script so

**Comment by Hellsing** [comment]
Could you be more precise with that statement please? Because that does not help us at all trying to help you.

**Comment by Requital** [comment]
Well i dont know how to precise it. Maybe that way: usually i have like 200-300 fps but when i run any script for ex. your kalista, my fps are like this: 80>60>40

**Comment by Requital** [comment]
sry 4 bed england

**Comment by Hellsing** [comment]
What I meant is when it occurs, for example just in fights, while farming, or even in base when standing still and pressing nothing.

**Comment by Requital** [comment]
anytime

**Comment by Requital** [comment]
pressing F5 is not solving it so

**Comment by Hellsing** [comment]
Can you try to inject just EloBuddy without any addons being enabled and give feedback if that is any better or not?

**Comment by Requital** [comment]
sure ill end my game and ill post results

**Comment by Requital** [comment]
injected only elobuddy and still drops

**Comment by Hellsing** [comment]
Then you should try reinstalling EloBuddy completely, there are enough forum threads which show you how to approach this. Right now EloBuddy itself only drops me from 200 fps to 190, which is totally acceptable.

**Comment by Requital** [comment]
Ok thanks :)

**Comment by Hellsing** [comment]
As you didn't report back I assume the issue has been resolved, thanks for reporting this anyways.
