### ISSUE TITLE
[Feature] Add TargetSelector for most stacks

### ISSUE THREAD

**Issue by jprzimba** [EloBuddy/EloBuddy.Issues#80]
Please add an option at target selector por players that have most Stack Like, Kalista and kIndred passive. It's too god for this champions

**Comment by jachicao** [comment]
added this champion's stack:
- Braum
- Darius
- Ekko
- Gnar
- Kalista
- Kennen
- Kindred (Passive and E)
- Tamn Kench
- Tristana
- Twitch
- Varus
- Vayne
- Velkoz
- Vi
