### ISSUE TITLE
Orbwalker and prediction needs tons of work

### ISSUE THREAD

**Issue by iiExcellence** [EloBuddy/EloBuddy.Issues#84]
The prediction is just flat out bad. I play corki a lot and when im shooting my rockets the enemy could be standing still and id shoot it a couple feet to the side of him. And my q's rarely hit moving targets. Orbwalking is OK but I mean it could be a ton better. Waveclearing seems to miss me tons of creeps and last hitting is okay just wish I could customize it because if feels like it misses ones I should be easily able to hit.. When the wave comes under tower I literally can not get a single minion even when it's last hittable i have to farm myself. The kiting also feels very sloppy it could be going TONS faster. I'd definitely use this program over any other program though so keep up the great work and keep working on these things. You guys will be the best community eventually

**Comment by jachicao** [comment]
I think it's an issue from your end, just take a look what they told here: https://www.elobuddy.net/topic/9713-feedback-orbwalker/page-12#entry175298.
Different settings, same champion.

If you think that isn't your fault, I'll need this:
Champion used, Ping, Addons used, Ticks per second.
