### ISSUE TITLE
FPS Drop in teamfights (possible core/sdk issue)

### ISSUE THREAD

**Issue by newchild** [EloBuddy/EloBuddy.Issues#90]
Report by JJ:
http://puu.sh/oaZm8/eca35f4838.png

**Comment by jachicao** [comment]
I think we will need a more specific report :(

**Comment by finndev** [comment]
Related (same user I assume): https://www.elobuddy.net/topic/25827-those-with-fps-problems-fix-for-nvidia-users/?hl=nvidia

-> closed
