### ISSUE TITLE
Missleaging names IsUnderTurret

### ISSUE THREAD

**Issue by LXMedia1** [EloBuddy/EloBuddy.Issues#91]
IsUnderEnemyturret() => is under Turret who is Enemy for this Unit
IsUnderHisturret() => is under Turret who is His own Turret
IsUnderTurret() => is Under Any Turret

should be imo

IsUnderEnemyTurret() => Is under Enemy Turret ( Enemy under Enemy turret = true )
IsUnderAllyTurret() => Is under Team Turret both depends on Objectmanager.Player team not on Unit team

**Comment by jachicao** [comment]
IsUnderAllyTurret() isn't great when you are comparing on the enemy side, because IsAlly only works based on your team. Thats why it's like that.

**Comment by LXMedia1** [comment]
should still be like that couse then its also possible to use it for Vector3 not like it is right now.
