### ISSUE TITLE
FPS Drop

### ISSUE THREAD

**Issue by chanchangreatness** [EloBuddy/EloBuddy.Issues#93]
As the title indicated, this problem is faced by many users of EloBuddy. Devs need to fix this issue as soon as possible to improve the use of EloBuddy to other players.

More power to the EloBuddy Community!

**Comment by jachicao** [comment]
We will need a better report to fix it.
For example, we need: Addons used, fps without addons.

**Comment by chanchangreatness** [comment]
Without addons: 120+ FPS
 -Clash: 70-80 FPS

With addons: 40-30 FPS
 -Clash: 20-30 FPS
Addon(s) used:
 -Mastermind

PC Specs:
-Processor: AMD A4-3400 with Radeon(tm) HD Graphics 2.70GHz
-RAM: 6GB
-Graphics: AMD Radeon HD 6410D (Onboard Graphics) w/ Dedicated Video Memory of 512mb
-Motherboard: ASRock A55M-VS

P.S. FPS still drops with or without addons as long as EloBuddy is injected. Tried to set the in-game settings as low as possible to the point that texts in-game are somewhat blurry (My screen resolution is 1280x1024, lowest screen resolution in-game was 1024x768, making texts blurry). Hope the developers of EloBuddy will reach this.

**Comment by coman3** [comment]
Looks like your computer isn't very powerful, which may be most of the problem. What kind of FPS do you get during team fights without EB Injected?

**Comment by chanchangreatness** [comment]
@coman3 about 70-80 FPS includes Very High setting for both Character Detail and Skill Detail while retaining the Environment Detail set to Medium

**Comment by SidaRevamped** [comment]
bansharp = 0 fps drop , elobuddy = +-50 fps drop , poblem come from code
